---
title: "Problem Set 2"
author: "Marc Ishak"
output:
  html_notebook:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Uni/2019T3/econ3203")

```

# Question 1
First, let's load our prefered packages and load the data into R
```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(gvlma)
library(broom)

df <- read_csv("data/pset2/dynamic.csv")  

```

## a

```{r}

regmod <- lm(static ~ dynamic, data = df)
regmod_sum <- summary(regmod)

regmod_sum

```
Hence the regression formula is static = `r regmod$coefficients[1]` + dynamic * `r regmod$coefficients[2]` + \(\epsilon\)

## b 

```{r, fig.width=8, fig.asp=1.5}
dev.new()
par(mfrow = c(3,2))
plot(regmod, which = 1:6)
```
```{r}
gvlma(regmod)

tidy(regmod, conf.int = T) %>% 
  ggplot(aes(term, estimate, color = term)) +
    geom_point() +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
    geom_hline(yintercept = 0)

```


##  c

```{r}
augment(regmod) %>% 
  # mutate(group = ifelse(.cooksd > 1, "A", "B")) %>%
  ggplot(aes(dynamic, static)) +
    geom_point(aes(col = .cooksd)) +
    geom_smooth(method = "lm", se = 0.95) +
    # scale_color_manual(values = c("B" = "#000000", "A" = "#ff0000"), labels = c("B" = "", "A" ="Outlier")) +
    labs(col = "Cooks Distance")
```

Yes, as there's a point with a [cooks distance](https://en.wikipedia.org/wiki/Cook%27s_distance)  >  1.


## d

```{r}

```